version: "3.8"
services:
  frontend-shoora:
    image: node:14-alpine
    volumes:
      - .:/app
    command: sh -c "node --version && npm --version && cd /app && npm i && node index.js"
    ports:
      - "3002:3000"